import type { Barber, Booking, Service, User, Review, BarberDaySchedule, BlockedSlot } from "@/types";

export const mockServices: Service[] = [
  {
    id: "s1",
    name: "Haircut",
    nameUz: "Soch olish",
    nameRu: "Стрижка",
    description: "Classic or modern haircut",
    descriptionUz: "Klassik yoki zamonaviy soch olish",
    descriptionRu: "Классическая или современная стрижка",
    price: 50000,
    duration: 30,
    icon: "✂️",
  },
  {
    id: "s2",
    name: "Beard Trim",
    nameUz: "Soqol olish",
    nameRu: "Стрижка бороды",
    description: "Professional beard grooming",
    descriptionUz: "Professional soqol parvarishi",
    descriptionRu: "Профессиональный уход за бородой",
    price: 30000,
    duration: 20,
    icon: "🧔",
  },
  {
    id: "s3",
    name: "Hair + Beard",
    nameUz: "Soch + Soqol",
    nameRu: "Волосы + Борода",
    description: "Full haircut and beard trim combo",
    descriptionUz: "To'liq soch va soqol olish",
    descriptionRu: "Полный комплекс: стрижка и борода",
    price: 70000,
    duration: 45,
    icon: "💈",
  },
  {
    id: "s4",
    name: "Kids Haircut",
    nameUz: "Bolalar soch olish",
    nameRu: "Детская стрижка",
    description: "Haircut for children under 12",
    descriptionUz: "12 yoshgacha bolalar uchun soch olish",
    descriptionRu: "Стрижка для детей до 12 лет",
    price: 35000,
    duration: 25,
    icon: "👦",
  },
  {
    id: "s5",
    name: "Hair Styling",
    nameUz: "Soch turmaklash",
    nameRu: "Укладка волос",
    description: "Professional hair styling",
    descriptionUz: "Professional soch turmaklash",
    descriptionRu: "Профессиональная укладка",
    price: 40000,
    duration: 30,
    icon: "💇",
  },
  {
    id: "s6",
    name: "Shave",
    nameUz: "Qirish",
    nameRu: "Бритьё",
    description: "Hot towel traditional shave",
    descriptionUz: "Issiq sochiq bilan an'anaviy qirish",
    descriptionRu: "Традиционное бритьё с горячим полотенцем",
    price: 25000,
    duration: 20,
    icon: "🪒",
  },
];

const defaultWorkingHours = {
  monday: { isOpen: true, open: "09:00", close: "19:00" },
  tuesday: { isOpen: true, open: "09:00", close: "19:00" },
  wednesday: { isOpen: true, open: "09:00", close: "19:00" },
  thursday: { isOpen: true, open: "09:00", close: "19:00" },
  friday: { isOpen: true, open: "09:00", close: "19:00" },
  saturday: { isOpen: true, open: "10:00", close: "17:00" },
  sunday: { isOpen: false, open: "00:00", close: "00:00" },
};

export const mockBarbers: Barber[] = [
  {
    id: "b1",
    name: "Aziz Karimov",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    bio: "Master barber with 8 years of experience. Specialist in modern fades and classic cuts.",
    bioUz: "8 yillik tajribaga ega usta sartarosh. Zamonaviy fade va klassik soch turmaklar bo'yicha mutaxassis.",
    bioRu: "Мастер-парикмахер с 8-летним опытом. Специалист по современным фейдам и классическим стрижкам.",
    phone: "+998901234567",
    rating: 4.9,
    reviewCount: 156,
    experience: 8,
    location: "Tashkent, Chilanzar",
    locationUz: "Toshkent, Chilonzor",
    locationRu: "Ташкент, Чиланзар",
    services: [mockServices[0], mockServices[1], mockServices[2], mockServices[4]],
    workingHours: defaultWorkingHours,
    gallery: [
      "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=300",
      "https://images.unsplash.com/photo-1503951914875-452c9b4ff80d?w=300",
      "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=300",
    ],
    isAvailable: true,
    slotDuration: 30,
  },
  {
    id: "b2",
    name: "Bobur Aliyev",
    avatar: "https://randomuser.me/api/portraits/men/45.jpg",
    bio: "Creative barber specializing in artistic designs and premium grooming services.",
    bioUz: "Badiiy dizayn va premium parvarishlash xizmatlari bo'yicha ixtisoslashgan ijodkor sartarosh.",
    bioRu: "Креативный барбер, специализирующийся на художественных дизайнах и премиум-услугах.",
    phone: "+998901234568",
    rating: 4.8,
    reviewCount: 132,
    experience: 6,
    location: "Tashkent, Yunusabad",
    locationUz: "Toshkent, Yunusobod",
    locationRu: "Ташкент, Юнусабад",
    services: [mockServices[0], mockServices[1], mockServices[2], mockServices[5]],
    workingHours: {
      ...defaultWorkingHours,
      saturday: { isOpen: true, open: "10:00", close: "18:00" },
    },
    gallery: [
      "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=300",
      "https://images.unsplash.com/photo-1585747860019-8e8e2e43e924?w=300",
      "https://images.unsplash.com/photo-1596728325488-58c87691e9af?w=300",
    ],
    isAvailable: true,
    slotDuration: 60,
  },
  {
    id: "b3",
    name: "Sardor Toshmatov",
    avatar: "https://randomuser.me/api/portraits/men/67.jpg",
    bio: "Experienced barber known for precision cuts and excellent customer service.",
    bioUz: "Aniq kesish va a'lo mijozlarga xizmat ko'rsatish bilan tanilgan tajribali sartarosh.",
    bioRu: "Опытный барбер, известный точными стрижками и отличным обслуживанием.",
    phone: "+998901234569",
    rating: 4.7,
    reviewCount: 98,
    experience: 5,
    location: "Tashkent, Mirzo Ulugbek",
    locationUz: "Toshkent, Mirzo Ulug'bek",
    locationRu: "Ташкент, Мирзо Улугбек",
    services: [mockServices[0], mockServices[2], mockServices[3], mockServices[4]],
    workingHours: defaultWorkingHours,
    gallery: [
      "https://images.unsplash.com/photo-1493256338651-d82f7acb2b38?w=300",
      "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=300",
      "https://images.unsplash.com/photo-1634302086887-13b2b3e6528f?w=300",
    ],
    isAvailable: true,
    slotDuration: 30,
  },
  {
    id: "b4",
    name: "Jasur Nematov",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    bio: "Young and talented barber with fresh ideas and trendy styles.",
    bioUz: "Yangi g'oyalar va zamonaviy uslublarga ega yosh va iqtidorli sartarosh.",
    bioRu: "Молодой и талантливый барбер со свежими идеями и модными стилями.",
    phone: "+998901234570",
    rating: 4.6,
    reviewCount: 74,
    experience: 3,
    location: "Tashkent, Sergeli",
    locationUz: "Toshkent, Sergeli",
    locationRu: "Ташкент, Сергели",
    services: [mockServices[0], mockServices[1], mockServices[3], mockServices[5]],
    workingHours: {
      ...defaultWorkingHours,
      sunday: { isOpen: true, open: "10:00", close: "15:00" },
    },
    gallery: [
      "https://images.unsplash.com/photo-1521490683712-35a1cb235d1c?w=300",
      "https://images.unsplash.com/photo-1599351431613-18ef1fdd27e1?w=300",
      "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=300",
    ],
    isAvailable: true,
    slotDuration: 45,
  },
  {
    id: "b5",
    name: "Timur Rashidov",
    avatar: "https://randomuser.me/api/portraits/men/55.jpg",
    bio: "Premium barber offering luxury grooming experience with top-quality products.",
    bioUz: "Yuqori sifatli mahsulotlar bilan hashamatli parvarishlash tajribasini taqdim etuvchi premium sartarosh.",
    bioRu: "Премиум-барбер, предлагающий роскошный уход с использованием высококачественных продуктов.",
    phone: "+998901234571",
    rating: 4.9,
    reviewCount: 203,
    experience: 10,
    location: "Tashkent, Yakkasaray",
    locationUz: "Toshkent, Yakkasaroy",
    locationRu: "Ташкент, Яккасарай",
    services: mockServices,
    workingHours: defaultWorkingHours,
    gallery: [
      "https://images.unsplash.com/photo-1585747860019-8e8e2e43e924?w=300",
      "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=300",
      "https://images.unsplash.com/photo-1493256338651-d82f7acb2b38?w=300",
    ],
    isAvailable: true,
    slotDuration: 30,
  },
  {
    id: "b6",
    name: "Otabek Mirzayev",
    avatar: "https://randomuser.me/api/portraits/men/78.jpg",
    bio: "Family-friendly barber with a warm atmosphere. Great with kids!",
    bioUz: "Iliq muhitga ega oilaviy sartarosh. Bolalar bilan ajoyib ishlaydi!",
    bioRu: "Семейный барбер с тёплой атмосферой. Отлично работает с детьми!",
    phone: "+998901234572",
    rating: 4.5,
    reviewCount: 89,
    experience: 7,
    location: "Tashkent, Olmazor",
    locationUz: "Toshkent, Olmazor",
    locationRu: "Ташкент, Олмазор",
    services: [mockServices[0], mockServices[2], mockServices[3]],
    workingHours: defaultWorkingHours,
    gallery: [
      "https://images.unsplash.com/photo-1596728325488-58c87691e9af?w=300",
      "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=300",
      "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=300",
    ],
    isAvailable: false,
    slotDuration: 30,
  },
];

export const mockUser: User = {
  id: "u1",
  name: "Shohruh",
  email: "shohruh@example.com",
  phone: "+998901112233",
  avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  role: "user",
  createdAt: "2024-01-15",
};

export const mockAdmin: User = {
  id: "admin1",
  name: "Admin",
  email: "admin@barberbook.uz",
  phone: "+998900000000",
  role: "admin",
  createdAt: "2024-01-01",
};

export const mockBarberUser: User = {
  id: "b1",
  name: "Aziz Karimov",
  email: "aziz@barberbook.uz",
  phone: "+998901234567",
  avatar: "https://randomuser.me/api/portraits/men/32.jpg",
  role: "barber",
  createdAt: "2024-01-01",
};

export const mockBookings: Booking[] = [
  {
    id: "bk1",
    userId: "u1",
    barberId: "b1",
    barberName: "Aziz Karimov",
    barberAvatar: "https://randomuser.me/api/portraits/men/32.jpg",
    services: [mockServices[0], mockServices[1]],
    date: "2026-02-20",
    time: "10:00",
    status: "confirmed",
    totalPrice: 80000,
    totalDuration: 50,
    createdAt: "2026-02-18",
  },
  {
    id: "bk2",
    userId: "u1",
    barberId: "b2",
    barberName: "Bobur Aliyev",
    barberAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
    services: [mockServices[2]],
    date: "2026-02-22",
    time: "14:00",
    status: "confirmed",
    totalPrice: 70000,
    totalDuration: 45,
    createdAt: "2026-02-18",
  },
  {
    id: "bk3",
    userId: "u1",
    barberId: "b5",
    barberName: "Timur Rashidov",
    barberAvatar: "https://randomuser.me/api/portraits/men/55.jpg",
    services: [mockServices[0], mockServices[1], mockServices[4]],
    date: "2026-02-10",
    time: "11:00",
    status: "completed",
    totalPrice: 120000,
    totalDuration: 80,
    createdAt: "2026-02-08",
  },
  {
    id: "bk4",
    userId: "u1",
    barberId: "b3",
    barberName: "Sardor Toshmatov",
    barberAvatar: "https://randomuser.me/api/portraits/men/67.jpg",
    services: [mockServices[0]],
    date: "2026-01-28",
    time: "16:00",
    status: "cancelled",
    totalPrice: 50000,
    totalDuration: 30,
    createdAt: "2026-01-25",
  },
];

export const mockReviews: Review[] = [
  {
    id: "r1",
    userId: "u1",
    userName: "Shohruh",
    userAvatar: "https://randomuser.me/api/portraits/men/1.jpg",
    barberId: "b1",
    rating: 5,
    comment: "Juda yaxshi usta! Har doim shu yerga kelaman.",
    createdAt: "2026-02-15",
  },
  {
    id: "r2",
    userId: "u2",
    userName: "Alisher",
    userAvatar: "https://randomuser.me/api/portraits/men/12.jpg",
    barberId: "b1",
    rating: 5,
    comment: "A'lo darajada! Tavsiya qilaman.",
    createdAt: "2026-02-10",
  },
  {
    id: "r3",
    userId: "u3",
    userName: "Nodir",
    userAvatar: "https://randomuser.me/api/portraits/men/25.jpg",
    barberId: "b2",
    rating: 4,
    comment: "Yaxshi xizmat, lekin biroz kutish kerak bo'ldi.",
    createdAt: "2026-02-08",
  },
  {
    id: "r4",
    userId: "u4",
    userName: "Bekzod",
    barberId: "b5",
    rating: 5,
    comment: "Eng yaxshi sartarosh! Premium xizmat.",
    createdAt: "2026-02-05",
  },
];

// Booked slots for demo
export const mockBookedSlots: Record<string, string[]> = {
  "b1-2026-02-20": ["10:00", "10:30", "14:00"],
  "b1-2026-02-21": ["09:00", "11:00", "15:00", "15:30"],
  "b2-2026-02-20": ["09:00", "09:30", "13:00"],
  "b2-2026-02-22": ["14:00", "14:30"],
  "b3-2026-02-20": ["10:00", "16:00"],
  "b5-2026-02-20": ["09:00", "09:30", "10:00", "10:30"],
};

// Barber custom day schedules (overrides default working hours for specific dates)
// Key: "barberId-date"
export const mockBarberDaySchedules: Record<string, BarberDaySchedule> = {
  "b1-2026-02-20": {
    barberId: "b1",
    date: "2026-02-20",
    slots: ["09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30"],
  },
  "b1-2026-02-21": {
    barberId: "b1",
    date: "2026-02-21",
    slots: ["09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30"],
  },
};

// Slots manually blocked by barber
export const mockBlockedSlots: BlockedSlot[] = [
  { barberId: "b1", date: "2026-02-20", time: "11:00" },
  { barberId: "b1", date: "2026-02-21", time: "13:00" },
];
